// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrHDx7K8gXhXyaM_X4K8BdWZ-Ig6bFSCA',
    appId: '1:423740269888:android:9b3fc7e7a561e65a2bc6a5',
    messagingSenderId: '423740269888',
    projectId: 'doctorapp-8bc30',
    storageBucket: 'doctorapp-8bc30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVbnSgfiu0lzrilWCChVRYhKfkQnyQeoU',
    appId: '1:423740269888:ios:5717460bc23f58bd2bc6a5',
    messagingSenderId: '423740269888',
    projectId: 'doctorapp-8bc30',
    storageBucket: 'doctorapp-8bc30.appspot.com',
    androidClientId: '423740269888-8bg3qdla4o8urpu4b8ugn938ahv1mncn.apps.googleusercontent.com',
    iosClientId: '423740269888-q6cssg8knehm4crt48n77mhptjq96clp.apps.googleusercontent.com',
    iosBundleId: 'com.vidcall.tws.youtube',
  );
}
